title: Learn Postgres
description: Postgres это просто
theme: just-the-docs

url: https://learn-postgres.foxelyss.ru

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
